version: "3.6"

services:

  tx-services-challenge:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tx_services_challenge
    environment:
      DB_USER: devuser
      DB_PWD: devuser
      DB_NAME: doodlesDB
      DB_HOST: my_mongodb
      DB_PORT: 27017
    volumes:
      - ./data/applogs:/tmp/logs
    ports:
      - 8080:8080
    depends_on:
      - mongo-database

  mongo-database:
    image: mongo
    container_name: my_mongodb
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: root 
      MONGO_INITDB_DATABASE: doodlesDB
    volumes:
      - ./init-mongo.js/:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017

  init-polls:
    build: ./init-polls
    links:
      - mongo-database
